services:
  chroma:
    image: chromadb/chroma:0.6.2
    ports:
      - "8000:8000"
    environment:
      - CHROMA_LOG_LEVEL=debug  # Enable detailed logs
    volumes:
      - ./infra/chromadbdata:/chromadb/data
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
